In [1]:
import pandas as pd
import numpy as np

In [2]:
raw=pd.read_csv(r'C:\Users\HP\Desktop\hotel_bookings.csv')
raw

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July                        27   
3                    July                        27   
4                    July                        27   
...                   ...                       ...   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0   
1                               1                        0   
2                               1                        0   
3                               1                        0   
4                               1                        0   
...                           ...                      ...   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
0                          0       2  ...    No Deposit    NaN     NaN   
1                          0       2  ...    No Deposit    NaN     NaN   
2                          1       1  ...    No Deposit    NaN     NaN   
3                          1       1  ...    No Deposit  304.0     NaN   
4                          2       2  ...    No Deposit  240.0     NaN   
...                      ...     ...  ...           ...    ...     ...   
119385                     5       2  ...    No Deposit  394.0     NaN   
119386                     5       3  ...    No Deposit    9.0     NaN   
119387                     5       2  ...    No Deposit    9.0     NaN   
119388                     5       2  ...    No Deposit   89.0     NaN   
119389                     7       2  ...    No Deposit    9.0     NaN   

       days_in_waiting_list customer_type     adr  \
0                         0     Transient    0.00   
1                         0     Transient    0.00   
2                         0     Transient   75.00   
3                         0     Transient   75.00   
4                         0     Transient   98.00   
...                     ...           ...     ...   
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0   
1                                 0                          0   
2                                 0                          0   
3             

In [3]:
raw.shape

(119390, 32)

In [4]:
raw1 =raw.copy()

In [5]:
print('Nan in each columns',raw1.isna().sum(),sep='\n')

Nan in each columns
hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16

In [6]:
raw1=raw1.drop(['company'],axis=1)
raw1=raw1.dropna(axis=0)

In [7]:
raw1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102894 entries, 3 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           102894 non-null  object 
 1   is_canceled                     102894 non-null  int64  
 2   lead_time                       102894 non-null  int64  
 3   arrival_date_year               102894 non-null  int64  
 4   arrival_date_month              102894 non-null  object 
 5   arrival_date_week_number        102894 non-null  int64  
 6   arrival_date_day_of_month       102894 non-null  int64  
 7   stays_in_weekend_nights         102894 non-null  int64  
 8   stays_in_week_nights            102894 non-null  int64  
 9   adults                          102894 non-null  int64  
 10  children                        102894 non-null  float64
 11  babies                          102894 non-null  int64  
 12  meal            

In [8]:
raw1.shape

(102894, 31)

In [9]:
raw1['hotel'].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [10]:
raw1['hotel'].value_counts()

City Hotel      71181
Resort Hotel    31713
Name: hotel, dtype: int64

In [11]:
raw1['hotel'] = raw1['hotel'].map({'Resort Hotel':0,'City Hotel':1})

In [12]:
raw1['hotel'].unique()

array([0, 1], dtype=int64)

In [13]:
raw1['hotel'].value_counts()

1    71181
0    31713
Name: hotel, dtype: int64

In [14]:
raw1['arrival_date_month'].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [15]:
raw1['arrival_date_month'].value_counts()

August       12672
July         11599
May          10087
June          9803
April         9746
October       9437
September     9411
March         8132
February      6445
December      5620
November      5396
January       4546
Name: arrival_date_month, dtype: int64

In [16]:
raw1['arrival_date_month'] = raw1['arrival_date_month'].map({'January':1,'February':2,'March':3,'April':4,'May':5,'June':6,'July':7,'August':8,'September':9,'October':10,'November':11,'December':12})

In [17]:
raw1['arrival_date_month'].value_counts()

8     12672
7     11599
5     10087
6      9803
4      9746
10     9437
9      9411
3      8132
2      6445
12     5620
11     5396
1      4546
Name: arrival_date_month, dtype: int64

In [18]:
raw1['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [19]:
raw['customer_type'].value_counts()

Transient          89613
Transient-Party    25124
Contract            4076
Group                577
Name: customer_type, dtype: int64

In [20]:
raw1['customer_type'] = raw1['customer_type'].map({'Transient':1,'Transient-Party':2,'Contract':3,'Group':4})

In [21]:
raw1['customer_type'].value_counts()

1    77756
2    20602
3     4063
4      473
Name: customer_type, dtype: int64

In [22]:
raw1['reservation_status'].unique()

array(['Check-Out', 'Canceled', 'No-Show'], dtype=object)

In [23]:
raw1['reservation_status'].value_counts()

Check-Out    62733
Canceled     39158
No-Show       1003
Name: reservation_status, dtype: int64

In [24]:
raw1['reservation_status']=raw1['reservation_status'].map({'Check-Out':0,'Canceled':1,'No-Show':3})

In [25]:
raw1['reservation_status'].value_counts()

0    62733
1    39158
3     1003
Name: reservation_status, dtype: int64

In [26]:
raw1['previous_cancellations'].unique()

array([ 0,  1,  2, 26, 25, 14,  3, 24, 21,  5, 13, 11,  6], dtype=int64)

In [27]:
raw1['previous_cancellations'].value_counts()

0     97339
1      5384
2        36
26       26
25       25
11       25
24       24
14       14
3         9
6         6
13        4
21        1
5         1
Name: previous_cancellations, dtype: int64

In [28]:
raw1['previous_cancellations'] = raw1['previous_cancellations'].map({0:0,1:1,2:1,3:1,4:1,5:1,6:1,11:1,13:1,14:1,19:1,21:1,24:1,25:1,26:1})

In [29]:
raw1['previous_cancellations'].unique()

array([0, 1], dtype=int64)

In [30]:
raw1['previous_cancellations'].value_counts()

0    97339
1     5555
Name: previous_cancellations, dtype: int64

In [31]:
raw1['meal'].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [32]:
raw1['meal'].value_counts()

BB           77638
HB           13421
SC           10334
Undefined      830
FB             671
Name: meal, dtype: int64

In [33]:
raw1['meal']=raw1['meal'].map({'BB':0,'HB':1,'SC':2,'Undefined':3,'FB':4})

In [34]:
raw1['meal'].value_counts()

0    77638
1    13421
2    10334
3      830
4      671
Name: meal, dtype: int64

In [35]:
raw1['market_segment'].unique()

array(['Corporate', 'Online TA', 'Direct', 'Offline TA/TO', 'Groups',
       'Complementary', 'Aviation'], dtype=object)

In [36]:
raw1['market_segment'].value_counts()

Online TA        56057
Offline TA/TO    23774
Groups           15661
Direct            6582
Corporate          692
Complementary      103
Aviation            25
Name: market_segment, dtype: int64

In [37]:
raw1['market_segment']=raw['market_segment'].map({'Online TA':0,'Offline TA/TO':1,'Groups':2,'Direct':3,'Corporate':4,'Complementary':5,'Aviation':7})

In [38]:
raw1['distribution_channel'].unique()

array(['Corporate', 'TA/TO', 'Direct', 'GDS'], dtype=object)

In [39]:
raw1['distribution_channel']=raw1['distribution_channel'].map({'Corporate':0,'TA/TO':1,'Direct':2,'GDS':3})

In [40]:
raw1['distribution_channel'].value_counts()

1    94575
2     7003
0     1125
3      191
Name: distribution_channel, dtype: int64

In [41]:
raw1['booking_changes'].unique()

array([ 0,  1,  2,  3,  5,  4, 17,  6,  8,  7, 10, 16,  9, 13, 12, 14, 15,
       18, 11], dtype=int64)

In [42]:
raw1['booking_changes'].value_counts()

0     88645
1     10020
2      3037
3       696
4       286
5        83
6        54
7        26
8        14
9         8
10        6
13        5
14        3
15        3
17        2
12        2
16        2
11        1
18        1
Name: booking_changes, dtype: int64

In [43]:
raw1['booking_changes'] = raw1['booking_changes'].map({0:0,1:1,2:1,3:1,4:1,5:1,6:1,7:1,8:1,9:1,10:1,11:1,12:1,13:1,14:1,15:1,16:1,17:1,18:1,20:1,21:1})

In [44]:
raw1['booking_changes'].unique()

array([0, 1], dtype=int64)

In [45]:
raw1['booking_changes'].value_counts()

0    88645
1    14249
Name: booking_changes, dtype: int64

In [46]:
raw1['required_car_parking_spaces'].unique()

array([0, 1, 2, 3], dtype=int64)

In [47]:
raw1['required_car_parking_spaces'].value_counts()

0    97463
1     5408
2       20
3        3
Name: required_car_parking_spaces, dtype: int64

In [48]:
raw1['required_car_parking_spaces'] = raw1['required_car_parking_spaces'].map({0:0,1:1,2:1,3:1,8:1})

In [49]:
raw1['required_car_parking_spaces'].unique()

array([0, 1], dtype=int64)

In [50]:
raw1['required_car_parking_spaces'].value_counts()

0    97463
1     5431
Name: required_car_parking_spaces, dtype: int64

In [51]:
raw1['total_of_special_requests'].unique()

array([0, 1, 3, 2, 4, 5], dtype=int64)

In [52]:
raw1['total_of_special_requests'].value_counts()

0    57956
1    30441
2    11964
3     2232
4      272
5       29
Name: total_of_special_requests, dtype: int64

In [53]:
raw1['total_of_special_requests'] = raw1['total_of_special_requests'].map({0:0,1:1,2:1,3:1,4:1,5:1})

In [54]:
raw1['total_of_special_requests'].unique()

array([0, 1], dtype=int64)

In [55]:
raw1['total_of_special_requests'].value_counts()

0    57956
1    44938
Name: total_of_special_requests, dtype: int64

In [56]:
raw1['reserved_room_type'].unique()

array(['A', 'C', 'D', 'E', 'G', 'F', 'H', 'B'], dtype=object)

In [57]:
raw1['reserved_room_type'].value_counts()

A    73265
D    17535
E     5457
F     2537
G     1809
B      992
C      765
H      534
Name: reserved_room_type, dtype: int64

In [58]:
raw1['reserved_room_type']=raw1['reserved_room_type'].map({'A':0,'D':1,'E':2,'F':3,'G':4,'B':5,'C':6,'H':7})

In [59]:
raw1['reserved_room_type'].value_counts()

0    73265
1    17535
2     5457
3     2537
4     1809
5      992
6      765
7      534
Name: reserved_room_type, dtype: int64

In [60]:
raw1['assigned_room_type'].unique()

array(['A', 'C', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'K'], dtype=object)

In [61]:
raw1['assigned_room_type']=raw1['assigned_room_type'].map({'A':0,'C':1,'D':2,'E':3,'G':4,'F':5,'I':6,'B':7,'H':8,'K':9})

In [62]:
raw['assigned_room_type'].value_counts()

A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: assigned_room_type, dtype: int64

In [63]:
raw1['deposit_type'].unique()

array(['No Deposit', 'Refundable', 'Non Refund'], dtype=object)

In [64]:
raw1['deposit_type']=raw1['deposit_type'].map({'No Deposit':0,'Refundable':1,'Non Refund':2})

In [65]:
raw1['deposit_type'].value_counts()

0    90324
2    12522
1       48
Name: deposit_type, dtype: int64

In [66]:
raw1=raw1.drop(['reservation_status_date'],axis=1)
raw1.head(3)

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
3      0            0         13               2015                   7   
4      0            0         14               2015                   7   
5      0            0         14               2015                   7   

   arrival_date_week_number  arrival_date_day_of_month  \
3                        27                          1   
4                        27                          1   
5                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
3                        0                     1       1  ...   
4                        0                     2       2  ...   
5                        0                     2       2  ...   

   assigned_room_type  booking_changes  deposit_type  agent  \
3                   0                0             0  304.0   
4                   0                0             0  240.0   
5                   0                0             0  240.0   

   days_in_waiting_list  customer_type   adr  required_car_parking_spaces  \
3                     0              1  75.0                            0   
4                     0              1  98.0                            0   
5                     0              1  98.0                            0   

   total_of_special_requests  reservation_status  
3                          0                   0  
4                          1                   0  
5                          1                   0  

[3 rows x 30 columns]

In [67]:
raw1['is_canceled'].unique()

array([0, 1], dtype=int64)

In [68]:
targets=np.where(raw1['is_canceled']>
                raw1['is_canceled'].median(),1,0)
targets

array([0, 0, 0, ..., 0, 0, 0])

In [69]:
raw1['is_canceled']=targets
raw1.head(3)

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
3      0            0         13               2015                   7   
4      0            0         14               2015                   7   
5      0            0         14               2015                   7   

   arrival_date_week_number  arrival_date_day_of_month  \
3                        27                          1   
4                        27                          1   
5                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
3                        0                     1       1  ...   
4                        0                     2       2  ...   
5                        0                     2       2  ...   

   assigned_room_type  booking_changes  deposit_type  agent  \
3                   0                0             0  304.0   
4                   0                0             0  240.0   
5                   0                0             0  240.0   

   days_in_waiting_list  customer_type   adr  required_car_parking_spaces  \
3                     0              1  75.0                            0   
4                     0              1  98.0                            0   
5                     0              1  98.0                            0   

   total_of_special_requests  reservation_status  
3                          0                   0  
4                          1                   0  
5                          1                   0  

[3 rows x 30 columns]

In [70]:
targets.shape

(102894,)

In [71]:
targets.sum()/targets.shape[0]

0.39031430404105194

In [72]:
unscaled_inputs=raw1.iloc[:,0::2]
unscaled_inputs.head(3)

hotel  lead_time  arrival_date_month  arrival_date_day_of_month  \
3      0         13                   7                          1   
4      0         14                   7                          1   
5      0         14                   7                          1   

   stays_in_week_nights  children  meal  market_segment  is_repeated_guest  \
3                     1       0.0     0             4.0                  0   
4                     2       0.0     0             0.0                  0   
5                     2       0.0     0             0.0                  0   

   previous_bookings_not_canceled  assigned_room_type  deposit_type  \
3                               0                   0             0   
4                               0                   0             0   
5                               0                   0             0   

   days_in_waiting_list   adr  total_of_special_requests  
3                     0  75.0                          0  
4                     0  98.0                          1  
5                     0  98.0                          1

In [73]:
unscaled_inputs.shape

(102894, 15)

In [74]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
        
    def fit(self,x,y=None):
        self.scaler.fit(x[self.columns],y)
        self.mean_=np.mean(x[self.columns])
        self.var_=np.var(x[self.columns])
        return self
        
    def transform(self,x,y=None,copy=None):
        init_col_order=x.columns
        x_scaled=pd.DataFrame(self.scaler.transform(x[self.columns]),columns=self.columns)
        x_not_scaled=x.loc[:,~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled,x_scaled],axis=1)[init_col_order]

In [75]:
unscaled_inputs.columns.values

array(['hotel', 'lead_time', 'arrival_date_month',
       'arrival_date_day_of_month', 'stays_in_week_nights', 'children',
       'meal', 'market_segment', 'is_repeated_guest',
       'previous_bookings_not_canceled', 'assigned_room_type',
       'deposit_type', 'days_in_waiting_list', 'adr',
       'total_of_special_requests'], dtype=object)

In [76]:
columns_to_omit=['hotel','arrival_date_month','customer_type','meal','reserved_room_type','assigned_room_type','deposit_type','market_segment','distribution_channel','previous_cancellations','booking_changes','required_car_parking_spaces','total_of_special_requests']

In [77]:
columns_to_scale=[x for x in unscaled_inputs.columns.values]

In [78]:
raw1_scaler=CustomScaler(columns_to_scale)

In [79]:
raw1_scaler.fit(unscaled_inputs)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['hotel', 'lead_time', 'arrival_date_month',
                      'arrival_date_day_of_month', 'stays_in_week_nights',
                      'children', 'meal', 'market_segment', 'is_repeated_guest',
                      'previous_bookings_not_canceled', 'assigned_room_type',
                      'deposit_type', 'days_in_waiting_list', 'adr',
                      'total_of_special_requests'],
             copy=None, with_mean=None, with_std=None)

In [80]:
scaled_inputs=raw1_scaler.transform(unscaled_inputs)

In [81]:
scaled_inputs

hotel  lead_time  arrival_date_month  arrival_date_day_of_month  \
0      -1.498178  -0.916973            0.134411                  -1.681462   
1      -1.498178  -0.907686            0.134411                  -1.681462   
2      -1.498178  -0.907686            0.134411                  -1.681462   
3      -1.498178  -0.954120            0.134411                  -1.681462   
4      -1.498178  -0.248328            0.134411                  -1.681462   
...          ...        ...                 ...                        ...   
119385       NaN        NaN                 NaN                        NaN   
119386       NaN        NaN                 NaN                        NaN   
119387       NaN        NaN                 NaN                        NaN   
119388       NaN        NaN                 NaN                        NaN   
119389       NaN        NaN                 NaN                        NaN   

        stays_in_week_nights  children      meal  market_segment  \
0                  -0.834057 -0.269991 -0.508331        3.270167   
1                  -0.309379 -0.269991 -0.508331       -0.768294   
2                  -0.309379 -0.269991 -0.508331       -0.768294   
3                  -0.309379 -0.269991  4.820269        2.260551   
4                   0.215299 -0.269991 -0.508331       -0.768294   
...                      ...       ...       ...             ...   
119385                   NaN       NaN       NaN             NaN   
119386                   NaN       NaN       NaN             NaN   
119387                   NaN       NaN       NaN             NaN   
119388                   NaN       NaN       NaN             NaN   
119389                   NaN       NaN       NaN             NaN   

        is_repeated_guest  previous_bookings_not_canceled  assigned_room_type  \
0               -0.119305                       -0.055914           -0.630709   
1               -0.119305                       -0.055914           -0.630709   
2               -0.119305                       -0.055914           -0.630709   
3               -0.119305                       -0.055914           -0.044050   
4               -0.119305                       -0.055914           -0.630709   
...                   ...                             ...                 ...   
119385                NaN                             NaN                 NaN   
119386                NaN                             NaN                 NaN   
119387                NaN                             NaN                 NaN   
119388                NaN                             NaN                 NaN   
119389                NaN                             NaN                 NaN   

        deposit_type  days_in_waiting_list       adr  \
0          -0.372846             -0.139359 -0.593344   
1          -0.372846             -0.139359 -0.133541   
2          -0.372846             -0.139359 -0.133541   
3          -0.372846             -0.139359 -0.033584   
4          -0.372846             -0.139359 -0.453404   
...              ...                   ...       ...   
119385           NaN                   NaN       NaN   
119386           NaN                   NaN       NaN   
119387           NaN                   NaN       NaN   
119388           NaN                   NaN       NaN   
119389           NaN                   NaN       NaN   

        total_of_special_requests  
0                       -0.880557  
1                        1.135644  
2                        1.135644  
3                        1.135644  
4                        1.135644  
...                           ...  
119385                        NaN  
119386                        NaN  
119387                        NaN  
119388                        NaN  
119389                        NaN  

[117884 rows x 15 columns]

In [82]:
unscaled_inputs.shape

(102894, 15)

In [83]:
from sklearn.model_selection import train_test_split

train_test_split(unscaled_inputs,targets)

[        hotel  lead_time  arrival_date_month  arrival_date_day_of_month  \
 38910       0         60                   7                         29   
 106572      1          8                   2                         22   
 97424       1         30                   9                         15   
 89913       1          2                   5                         26   
 26871       0        205                   8                          6   
 ...       ...        ...                 ...                        ...   
 7475        0         18                   8                         11   
 33326       0          0                   2                         19   
 90881       1        137                   6                         10   
 64868       1         46                   3                         18   
 38011       0         62                   7                          5   
 
         stays_in_week_nights  children  meal  market_segment  \
 38910               

In [84]:
x_train,x_test,y_train,y_test=train_test_split(unscaled_inputs,targets,train_size=0.8,random_state=20)
print(x_train.shape,y_train.shape)

(82315, 15) (82315,)


In [85]:
print(x_test.shape,y_test.shape)

(20579, 15) (20579,)


In [86]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [87]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [88]:
reg.score(x_train,y_train)

0.7561440806657352

In [89]:
model_outputs=reg.predict(x_train)
model_outputs==y_train

array([ True,  True,  True, ...,  True,  True,  True])

In [90]:
reg.intercept_

array([-0.40364811])

In [91]:
reg.coef_

array([[-0.05157177,  0.00395317, -0.02294077, -0.00617171,  0.01821614,
         0.24663795, -0.18869574, -0.5939341 , -0.02158308, -0.17670973,
        -0.16545045,  2.19430752, -0.00317117,  0.00595266, -1.41408923]])

In [92]:
feature_name=unscaled_inputs.columns.values

In [93]:
summary_table=pd.DataFrame(columns=['feature_name'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

feature_name  coefficient
0                            hotel    -0.051572
1                        lead_time     0.003953
2               arrival_date_month    -0.022941
3        arrival_date_day_of_month    -0.006172
4             stays_in_week_nights     0.018216
5                         children     0.246638
6                             meal    -0.188696
7                   market_segment    -0.593934
8                is_repeated_guest    -0.021583
9   previous_bookings_not_canceled    -0.176710
10              assigned_room_type    -0.165450
11                    deposit_type     2.194308
12            days_in_waiting_list    -0.003171
13                             adr     0.005953
14       total_of_special_requests    -1.414089

In [94]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

feature_name  coefficient
0                        Intercept    -0.403648
1                            hotel    -0.051572
2                        lead_time     0.003953
3               arrival_date_month    -0.022941
4        arrival_date_day_of_month    -0.006172
5             stays_in_week_nights     0.018216
6                         children     0.246638
7                             meal    -0.188696
8                   market_segment    -0.593934
9                is_repeated_guest    -0.021583
10  previous_bookings_not_canceled    -0.176710
11              assigned_room_type    -0.165450
12                    deposit_type     2.194308
13            days_in_waiting_list    -0.003171
14                             adr     0.005953
15       total_of_special_requests    -1.414089

In [95]:
summary_table['Odds_ratio']=np.exp(summary_table.coefficient)
summary_table

feature_name  coefficient  Odds_ratio
0                        Intercept    -0.403648    0.667879
1                            hotel    -0.051572    0.949735
2                        lead_time     0.003953    1.003961
3               arrival_date_month    -0.022941    0.977320
4        arrival_date_day_of_month    -0.006172    0.993847
5             stays_in_week_nights     0.018216    1.018383
6                         children     0.246638    1.279716
7                             meal    -0.188696    0.828038
8                   market_segment    -0.593934    0.552151
9                is_repeated_guest    -0.021583    0.978648
10  previous_bookings_not_canceled    -0.176710    0.838023
11              assigned_room_type    -0.165450    0.847512
12                    deposit_type     2.194308    8.973785
13            days_in_waiting_list    -0.003171    0.996834
14                             adr     0.005953    1.005970
15       total_of_special_requests    -1.414089    0.243147

In [96]:
reg.score(x_test,y_test)

0.7559648185043005

In [97]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.96259554, 0.03740446],
       [0.6060236 , 0.3939764 ],
       [0.62251958, 0.37748042],
       ...,
       [0.89175416, 0.10824584],
       [0.29001104, 0.70998896],
       [0.83314381, 0.16685619]])

In [98]:
predicted_proba.shape

(20579, 2)

In [99]:
predicted_proba[:,1]

array([0.03740446, 0.3939764 , 0.37748042, ..., 0.10824584, 0.70998896,
       0.16685619])